feat: change transaction/address api to /api/transactions
PayButton/paybutton-server pull request #118
Opened 2022-06-18 15:47 UTC by alcipir

Description: change transaction/address api to api/transactions

Test Plan: `make dev` then open up `http://localhost:3000/api/transactions/bitcoincash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7q9ayphulp` for instance, remember to add a valid bchd instance on your .env or .env.local file: `GRPC_NODE_URL=bchd.fountainhead.cash` 

trying to open up `http://localhost:3000/api/transactions/` should throw an error.

2022-06-19 22:32 UTC, Klakurka commented
Can't get it working no matter what I try.

2022-06-20 12:58 UTC, chedieck requested changes

2022-06-20 12:58 UTC, chedieck commented on constants/index.ts
> +  ADDRESS_NOT_PROVIDED_400: { statusCode: 400, message: 'Missing Address parameter' }
To keep consistency with the rest of the `..._NOT_PROVIDED_400` errors, I think this error message would be better as `"'address' not provided"`.

2022-06-20 12:58 UTC, chedieck commented on pages/api/transactions/[address].ts
> +      res.status(ADDRESS_NOT_PROVIDED_400.statusCode).send({ message: ADDRESS_NOT_PROVIDED_400 })
Here it should be `...message: ADDRESS_NOT_PROVIDED_400.message})`

2022-06-20 12:58 UTC, chedieck commented on pages/api/transactions/[address].ts
> +    const { address } = req.query
I think is best to wrap all of this inside a `if (req.method == 'GET') {` so the endpoint ignores all other kinds of requests

2022-06-20 12:58 UTC, chedieck commented on pages/api/transactions/[address].ts
> +    const response = await getAddress(address)
Values that come from `req.query` can be either `string` or `string[]`, so you have to address this second case or typescript will complain about it.

2022-06-20 12:58 UTC, chedieck commented on pages/api/transactions/[address].ts
> +  } catch (e) {
Here is necessary to type the `e` variable, else typescript complains about it too.

2022-06-20 23:48 UTC, chedieck commented
> > `GRPC_NODE_URL=bchd.fountainhead.cash` gives 14 DNS RESOLUTION FAILED
> 
> this should be a connection error, make sure it is `GRPC_NODE_URL=bchd.fountainhead.cash`
> 
> the node could have gone offline for a bit. (accidentally edited your comment, using github app on mobile)

Indeed, I don't know how I didn't see that, it works now

2022-06-22 10:53 UTC, chedieck commented on pages/api/transactions/[address].ts
> +    const response = await getAddress(address)
I don't understand this, indeed here the tests are working, but the same thing is being done in #124 and the tests there are failing (I left a comment there)

2022-06-23 21:01 UTC, Gattaca1 requested changes

2022-06-23 21:01 UTC, Gattaca1 commented on tests/integration-tests/api.test.ts
> +  it('Should return HTTP 400 (Bad Request) if no address specified', async () => {
its testing for "no transaction id", rather than "no address"

2022-06-23 21:10 UTC, Klakurka commented
Not providing an address takes us to the admin page 404 which should be changed at some point. We can make a new task for that.

2022-06-23 21:11 UTC, Gattaca1 commented
![Screenshot from 2022-06-23 14-09-54](https://user-images.githubusercontent.com/7704588/175400472-76b69be1-db0f-4850-bac5-d3f07b446cc1.png)

The API should respond with a 400 error to bad requests

2022-06-23 21:11 UTC, Klakurka approved these changes
Assuming it's more than a few minutes to change, let's make a new task for an API-specific 404 reponse (or whatever for handling a bad request).

2022-06-23 21:12 UTC, Gattaca1 commented
API should never respond with 404

2022-06-23 21:30 UTC, Gattaca1 approved these changes

2022-06-23 21:31 UTC, merged