ci: github action to run integration tests on every PR to master
PayButton/paybutton-server pull request #123
Opened 2022-06-22 00:47 UTC by amphetamarina

Description: adds github action to run integration tests for every Pull Request to `master` branch.

Test Plan: check `Checks` tab above, it should be running integration tests. 

Depends on #133

2022-06-22 17:27 UTC, Gattaca1 requested changes
Can't run locally, trying to figure it out.

2022-06-22 18:12 UTC, Gattaca1 approved these changes

2022-06-23 15:10 UTC, chedieck requested changes
Left a remark, also now that we fixed the integrations tests, let's try running the check again after merging master into it.

2022-06-23 19:46 UTC, Klakurka submitted a review, later dismissed

2022-06-23 20:01 UTC, Gattaca1 approved these changes

2022-06-23 20:11 UTC, chedieck approved these changes

2022-06-23 20:20 UTC, Gattaca1 approved these changes

2022-06-23 20:21 UTC, merged