Refactor/rename paybutton address
PayButton/paybutton-server pull request #178
Opened 2022-07-19 19:06 UTC by chedieck

**Description:**
Basically, I ran two commands for string replace across the code:
`'paybuttonAddress' -> 'address'`
`'PaybuttonAddress' -> 'Address'`
... and then solved some minor problems like repeated constant values.

**Test:**
There should be no changes in any functionality.

Depends on:

- [ ] #173 
- [ ] #176

2022-07-25 19:10 UTC, Klakurka requested changes
Fix conflicts.

2022-07-25 19:18 UTC, chedieck commented
> Fix conflicts.

Done

2022-07-25 21:43 UTC, Klakurka approved these changes

2022-07-25 21:43 UTC, Klakurka commented on components/Paybutton/PaybuttonList.tsx
> +            {paybutton.addresses.map(item => (<li key={item.address.address}> {item.address.address}</li>))}
`address.address` kinda sucks but if everyone else is ok with it then ok.

2022-07-26 20:44 UTC, Gattaca1 approved these changes

2022-07-26 20:46 UTC, Klakurka approved these changes

2022-07-26 20:46 UTC, merged