[Issue #168] feat: add balance api
PayButton/paybutton-server pull request #186
Opened 2022-07-25 04:56 UTC by amphetamarina

Description: Related to #168. Adds a balance endpoint, with an alias for compatibility with the old API version.

Test Plan: `make dev`, then:

`http://localhost:3000/address/balance/bitcoincash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7q9ayphulp`
`http://localhost:3000/api/balance/bitcoincash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7q9ayphulp`

Both endpoints should work.

2022-07-25 06:40 UTC, Klakurka commented
For #168

2022-07-26 02:52 UTC, Klakurka commented
We do get an output but I'm not sure how to best test this against the client without running it live for a bit.

2022-07-26 17:39 UTC, chedieck commented
Some questions/remarks:
1. Isn't there a fast way to check the balance than adding all transactions outputs ourselves? If we try to run the endpoint for some address with a lot of transactions, such as `qzkyhguy920rs3l93kcd27sl9a8ft5hx9g2nvg8e22`, the request takes forever.
2. I think we should return the value as a decimal, and not in satoshis, as we are doing in the DB. I have used `return new Prisma.Decimal(satoshis).dividedBy(10e8)` for that end.

2022-07-26 17:40 UTC, chedieck requested changes
Some questions/remarks:
1. Isn't there a fast way to check the balance than adding all transactions outputs ourselves? If we try to run the endpoint for some address with a lot of transactions, such as `qzkyhguy920rs3l93kcd27sl9a8ft5hx9g2nvg8e22`, the request takes forever.
2. I think we should return the value as a decimal, and not in satoshis, as we are doing in the DB. I have used `return new Prisma.Decimal(satoshis).dividedBy(10e8)` for that end.

2022-07-26 18:37 UTC, chedieck commented on pages/api/balance/[address].ts
> +    const address = req.query.address as string
also, probably best to make this line `const address = parseAddress(req.query.address as string) ` so that the default parsing is executed

2022-07-29 23:16 UTC, Klakurka commented
I'll ask if there's a call we can make to return the balance

2022-07-30 00:54 UTC, Klakurka commented
Doesn't look like BCHD has any way to get the address balances on its own unfortunately.

2022-08-09 05:13 UTC, Klakurka approved these changes
I didn't test that this was working for the client but even if it's not working, it gets us closer to the goal. We can test it either live or once https://github.com/PayButton/paybutton/pull/156 is merged.

2022-08-09 05:15 UTC, Klakurka requested changes
Let's just make sure tests are passing before merging.

2022-08-09 07:29 UTC, Klakurka submitted a review, later dismissed

2022-08-09 18:31 UTC, chedieck requested changes

2022-08-09 18:31 UTC, chedieck commented on utils/validators.ts
> +  if (addressString === '' || addressString === undefined) throw new Error(RESPONSE_MESSAGES.ADDRESS_NOT_PROVIDED_400.message)
Since this check is being made, shouldn't the typing for the function be `... = function (addressString: string | undefined)` ?

2022-08-09 18:31 UTC, chedieck commented on pages/api/balance/[address].ts
> +      const response = await getBCHBalance(address)
There is now a utility function to convert from satoshis to unit value, check `utils/index.ts`'s `satoshisToUnit`

2022-08-10 04:38 UTC, Klakurka submitted a review, later dismissed

2022-08-10 13:04 UTC, chedieck commented on pages/api/balance/[address].ts
> +      const balance = satoshisToUnit(new Decimal(response), xecaddr.Format.Cashaddr)
`await` statement missing here, making the response return an empty JSON instead of the balance

2022-08-10 18:35 UTC, Gattaca1 approved these changes

2022-08-10 19:40 UTC, chedieck approved these changes

2022-08-10 19:43 UTC, merged