[Issue #191] feat: seed mock paybuttons
PayButton/paybutton-server pull request #192
Opened 2022-07-29 13:39 UTC by chedieck

Description:
Creates some PayButtons automatically, to simplify developing & testing.
![image](https://user-images.githubusercontent.com/21281174/181771873-b053bc7e-dd34-4066-8a65-2b4e2bba34d5.png)

Test Plan:
Recreate the containers with `make reset-dev` or simply reset the migrations with `yarn docker mr` and check if the following buttons were created for the default dev user.

2022-07-29 19:09 UTC, Klakurka requested changes
`http://localhost:3000/api/transactions/sync/bitcoincash:qzqh7ej2vz26a9xaxq7capzfwgxt5gem9g8rvfxc5t` should work right away but doesn't for me somehow.

`{"statusCode":500,"message":"3 INVALID_ARGUMENT: invalid address"}`

2022-07-29 19:34 UTC, chedieck commented
> `http://localhost:3000/api/transactions/sync/bitcoincash:qzqh7ej2vz26a9xaxq7capzfwgxt5gem9g8rvfxc5t` should work right away but doesn't for me somehow.
> 
> `{"statusCode":500,"message":"3 INVALID_ARGUMENT: invalid address"}`

Weird, I just tried that after running `make reset-dev` and it worked fine. Did you do that too? I think depending on which branch you are coming from simply `yarn docker mr` is not gonna work. Also, did you have the `.env` file with the `GRPC_NODE_URL`?

2022-07-30 00:43 UTC, Klakurka approved these changes
Forgot to connect to a BCHD node.

Maybe we can change the error message to indicate that the node isn't connected instead of invalid address?

2022-08-01 17:02 UTC, Gattaca1 approved these changes

2022-08-01 17:02 UTC, merged