Feat/add xec client
PayButton/paybutton-server pull request #196
Opened 2022-08-01 19:12 UTC by chedieck

Description:
Turns `bchdService` into `grpcService` and makes it so that it accepts both XEC and BCH addresses. The environment variable `GRPC_NODE_URL` was replaced by `GRPC_BCH_NODE_URL` and `GRPC_XEC_NODE_URL`,
 

Test Plan:
1. Edit the `.env` file to include a BCH and XEC node, example:
```
GRPC_BCH_NODE_URL=bchd.fountainhead.cash:443  
GRPC_XEC_NODE_URL=grpc.fabien.cash:8335   
```
2. Run `make reset-dev`
3. After the containers are up, try:
```
curl http://localhost:3000/api/transactions/sync/qzqh7ej2vz26a9xaxq7capzfwgxt5gem9g8rvfxc5t
curl http://localhost:3000/api/transactions/sync/qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7quss2vxek
``` 
4. Now, after logging in to the dev user, go to http://localhost:3000/buttons and check that the  transactions are visible there.

2022-08-02 15:40 UTC, Klakurka commented
I can't get this to compile.

2022-08-02 18:22 UTC, chedieck commented
> I can't get this to compile.

Can you post the errors you're getting?

2022-08-05 19:15 UTC, Klakurka commented on README.md
> +- Set `GRPC_BCH_NODE_URL` and `GRPC_XEC_NODE_URL` environment variables in `.env.local` or `.env` to a **BCHD** and **XECD** node, respectively, to get access to their API.
Makes sense to me to allow them to enter only one of them if they want to but we should probably make supporting that its own task.

2022-08-07 21:17 UTC, Klakurka requested changes
I'm getting this on the XEC call:

`{"statusCode":500,"message":"14 UNAVAILABLE: DNS resolution failed"}`

2022-08-08 14:20 UTC, chedieck commented
> I'm getting this on the XEC call:
> 
> `{"statusCode":500,"message":"14 UNAVAILABLE: DNS resolution failed"}`

I am getting the same, though while trying to fix the bug I found out that _ocasionally_ it works. I think the problem is in the node, but I am still trying to confirm that.

2022-08-08 14:27 UTC, chedieck commented
update: this now depends on #201. Edited description accordingly.

2022-08-09 04:54 UTC, Klakurka approved these changes

2022-08-09 04:56 UTC, merged