Feat/buttons UI
PayButton/paybutton-server pull request #214
Opened 2022-08-17 21:01 UTC by johnkuney

General updates of buttons page ui
- style updates
- modal for button creation
- transaction table

2022-08-17 21:50 UTC, Klakurka approved these changes

2022-08-17 22:40 UTC, Klakurka requested changes
Let's use commas on the amounts.

2022-08-17 23:42 UTC, Klakurka commented
ID and time stamp can be updated to something better at some point.

2022-08-18 15:47 UTC, johnkuney commented
Okay added

2022-08-18 17:25 UTC, Klakurka requested changes
Still an issue for me:

![image](https://user-images.githubusercontent.com/4713204/185457069-9a8448f4-61a5-4c17-9f26-8d38293c27a0.png)

Should format the numbers so that 2 decimals are always showing and also using commas.

2022-08-18 17:31 UTC, johnkuney commented
hmm okay. Are you seeing these transactions on the dev account? Cause I actually dont see any, so was using some mock data instead but must be strings instead of numbers or something. Will get it sorted though. 

Another thought, should I make the transaction ids link to that transaction on the block explorer (and for bch ones maybe blockchair?)

2022-08-18 17:35 UTC, Klakurka commented
Maybe we can get a 2nd reviewer to confirm what they see.

For the transactions, let's use the tx hashes instead of an "ID" as I'm not sure what that is.

2022-08-18 22:04 UTC, johnkuney commented
Okay was able to get the transactions working. Yeah my bad, hash makes more sense. Added number formatting, ticker based on address, and links to explorers

2022-08-19 13:32 UTC, chedieck commented on components/Paybutton/paybutton.module.css
> +  transition: all ease-in-out 200ms;
I find this `200ms` too slow

2022-08-19 13:38 UTC, chedieck requested changes
LGTM, I just left a remark for the animation transition that I found slow, don't know if others agree

2022-08-19 15:56 UTC, Klakurka requested changes
- time stamp should be a date, probably use the the user's local date format or whatever we're using on the site already if we are.
- would be nice if the hash column extended out to show the entire thing without the ellipsis if there's room (on larger screens) so people can more easily copy+paste them. OR add a copy button.

2022-08-19 15:58 UTC, johnkuney commented
For sure, can add those 
And sure animation could be a bit quicker, changed timing 100ms

2022-08-19 21:25 UTC, johnkuney commented
okay added, times should be local, using moment.js

2022-08-20 05:30 UTC, Klakurka approved these changes

2022-08-20 05:48 UTC, merged