[Issue #155] feat: network page styles
PayButton/paybutton-server pull request #216
Opened 2022-08-23 16:03 UTC by johnkuney

Style updates for the network page

2022-08-23 17:51 UTC, Gattaca1 approved these changes
LGTM

2022-08-24 02:41 UTC, Klakurka requested changes
How about adding an icon to the 'connected' status? Or a different font colour for connects vs not connected?

2022-08-24 15:58 UTC, johnkuney commented
For sure, added

2022-08-25 00:32 UTC, Klakurka approved these changes

2022-08-25 04:54 UTC, merged