[Issue #154] feat: add wallet services
PayButton/paybutton-server pull request #255
Opened 2022-10-04 17:35 UTC by chedieck

Description:
Add a `walletService.ts` file and tests for it.

Test Plan:
Should be covered by `tests/unittests/walletsService.test.ts`

2022-10-05 22:21 UTC, Gattaca1 commented
could you rebase to include the dependant branch?

2022-10-06 22:59 UTC, Gattaca1 requested changes
Can't create a wallet from the UI: 
![Screenshot from 2022-10-06 15-49-25](https://user-images.githubusercontent.com/7704588/194433558-da32a36e-cf87-4884-9a9f-bfefbbe32d52.png)

2022-10-07 05:20 UTC, chedieck commented
> Can't create a wallet from the UI: ![Screenshot from 2022-10-06 15-49-25](https://user-images.githubusercontent.com/7704588/194433558-da32a36e-cf87-4884-9a9f-bfefbbe32d52.png)

The UI is indeed not supposed to be working: it is still using mocked data

2022-10-07 21:37 UTC, Gattaca1 approved these changes

2022-10-07 21:38 UTC, merged