[Issue #247] improvements:dashboard
PayButton/paybutton-server pull request #277
Opened 2022-10-17 22:16 UTC by johnkuney

Fixes for issue #247 
- Have minimum Y-axis value always be 0
- Add '$' prefix to tooltips
- Format (add commas) to chart values and header 

will address the new "all" button in another PR

2022-10-18 19:56 UTC, ScottMcDermid requested changes
Dashboard changes look good.
Can you convert `./utils/general.js` into TypeScript? That way, we can maybe combine `general.ts` and `index.ts`.

2022-10-19 03:35 UTC, johnkuney commented
For sure, added

2022-10-19 06:34 UTC, Klakurka approved these changes

2022-10-19 08:35 UTC, ScottMcDermid approved these changes

2022-10-19 08:36 UTC, merged