[Issue #246] feat: 'All' option for dashboard charts
PayButton/paybutton-server pull request #286
Opened 2022-10-26 22:23 UTC by johnkuney

Adding an all option to the dashboard charts. Also fixed a few bugs that were causing sub $0.01 transactions to not register, and causing some date misalignments in the charts 

Test plan: Run the app and test out the all button, and see if the transactions line up on the chart

2022-10-27 07:45 UTC, Klakurka requested changes
Definitely better.

Only issue I saw was this when there were no data points >0 in the range (showing negative values in the Y-axis:

![image](https://user-images.githubusercontent.com/4713204/198222148-68ec01a0-0867-4138-b786-32a4b5d42d20.png)

2022-10-27 18:11 UTC, johnkuney commented
Good call, should be good now

2022-10-27 22:07 UTC, ScottMcDermid approved these changes
Looks good!

2022-10-28 02:25 UTC, Klakurka approved these changes

2022-10-28 02:25 UTC, merged