Feat/delete paybutton
PayButton/paybutton-server pull request #303
Opened 2022-11-08 15:13 UTC by chedieck

Description:
Solves #245. Users can delete paybuttons from the frontend (I made a 

Test plan:

2022-11-08 17:35 UTC, johnkuney requested changes
I'm seeing some display issues on the buttons page.
And actually there should already be some UI in place for deleting. If you you go to the button detail page and click the pencil icon, there is a delete button. If we can get this functionality there, that'd be ideal
<img width="1227" alt="Screen Shot 2022-11-08 at 11 27 16 AM" src="https://user-images.githubusercontent.com/31288518/200635599-b24fc123-ac32-4e16-b4fd-70602a9b2eb2.png">
<img width="875" alt="Screen Shot 2022-11-08 at 11 27 10 AM" src="https://user-images.githubusercontent.com/31288518/200635602-f2772500-2eaf-4876-b1d6-4d8153241efb.png">
<img width="1343" alt="Screen Shot 2022-11-08 at 11 26 51 AM" src="https://user-images.githubusercontent.com/31288518/200635603-7502417e-141c-491d-9c92-47845034eb12.png">

2022-11-09 12:45 UTC, chedieck commented
> I'm seeing some display issues on the buttons page. 

Indeed, I didn't care about that however; I just tried to make a pipeline that worked and leave the front end for you :shrug: (it would take a lot longer for me to brute-force the CSS into making it work)

> And actually there should already be some UI in place for deleting. If you you go to the button detail page and click the pencil icon, there is a delete button. If we can get this functionality there, that'd be ideal

Nice, I didn't know that. In this case, I will remove the ugly buttons from the button list and move this logic there.

2022-11-09 20:06 UTC, chedieck commented
Ready for review after dependency PRs are merged.

2022-11-10 03:57 UTC, Klakurka approved these changes

2022-11-10 19:47 UTC, merged