fix: add openssl1.1-compat to alpine node container
PayButton/paybutton-server pull request #339
Opened 2022-12-13 05:17 UTC by chedieck

Fixes the:
```
Error: Unable to require('/home/node/src/node_modules/@prisma/engines/libquery_engine-linux-musl.so.node')
Error loading shared library libssl.so.1.1: No such file or directory (needed by .../node_modules/prisma/libquery_engine-linux-musl.so.node)
```
 error.

2022-12-13 05:39 UTC, Klakurka requested changes
Mine is still stuck in a loop when building on this branch.

2022-12-13 08:41 UTC, Klakurka commented
Yep... so maybe somebody else can see if it's working for them.

2022-12-13 17:29 UTC, johnkuney commented
Its working for me

2022-12-18 01:12 UTC, ScottMcDermid approved these changes
Works for me

2022-12-18 01:13 UTC, Klakurka approved these changes

2022-12-18 01:13 UTC, merged