chore: add makefile and update README for mysql
PayButton/paybutton-server pull request #49
Opened 2022-04-08 05:08 UTC by alcipir

2022-04-14 19:10 UTC, Gattaca1 commented
As David suggested, moving this comment from Telegram to here
![Screenshot from 2022-04-09 21-59-43](https://user-images.githubusercontent.com/7704588/163459835-c9582288-7b4b-450e-bce3-e6ae5d6fc9f0.png)

are you using `sudo` to run make?
i have a permission error i haven't bothered to track down yet when running `make dev`, but `sudo make dev` fixes it
theres a lot of different things happening with this branch, i'm not sure which change is the issue

2022-04-16 16:00 UTC, alcipir commented
Updates: 

- Removed init-db step, now `make dev` should build and run the scripts necessary to have the paybutton server working
- Added instructions on how to get testing credentials to add to .env.local

2022-04-21 06:00 UTC, Gattaca1 commented
Could you add testing credentials from supertoken to .env?

Also I'm still getting an error here 

![Screenshot from 2022-04-20 22-32-12](https://user-images.githubusercontent.com/7704588/164383424-3f38d340-3921-4872-9dc7-e333c5452d56.png)

2022-04-22 20:20 UTC, alcipir commented
Just pushed a fix that only show social logins as long as you provide some credentials on .env file. (So it shouldn't break your app if you don't have it) 

Let me know of any more issues, and if needed testing credentials, hit me up on telegram @Gattaca1

2022-04-27 21:31 UTC, Klakurka requested changes

2022-04-27 21:31 UTC, Klakurka commented on .env
> +GRPC_NODE_URL=bchd.greyh.at:8335
Where did this URL come from? We have our own BCHD node.

2022-04-27 21:31 UTC, Klakurka commented on README.md
> +- Run the following make command to build/pull the relevant docker images and run the server locally:
Doesn't look related to what the branch is supposed to be so should be committed separately.

2022-04-27 21:31 UTC, Klakurka commented on README.md
> +- Run the following make command to build/pull the relevant docker images and run the server locally:
Doesn't look related to what the branch is supposed to be so should be committed separately.

2022-04-27 21:31 UTC, Klakurka commented on config/frontendConfig.tsx
> +
Goes for all the social login stuff (should be in a different branch).

2022-04-27 21:31 UTC, Klakurka commented on config/frontendConfig.tsx
> +
Goes for all the social login stuff (should be in a different branch).

2022-04-27 21:31 UTC, Klakurka commented on docker-compose.yml
> +      - mysql
Adding in MySQL should have been its own branch, separated from the "add a paybutton" stuff.

https://ourmachinery.com/post/step-by-step-programming-incrementally/

2022-04-27 21:31 UTC, Klakurka commented on docker-compose.yml
> +      - mysql
Adding in MySQL should have been its own branch, separated from the "add a paybutton" stuff.

https://ourmachinery.com/post/step-by-step-programming-incrementally/

2022-04-27 21:32 UTC, Klakurka requested changes

2022-04-27 21:32 UTC, Klakurka commented on .env
> +GRPC_NODE_URL=bchd.greyh.at:8335
Where did this URL come from? We have our own BCHD node.

2022-04-28 18:40 UTC, Gattaca1 commented
There are a ton of features in this branch, lets break it down some so its easier to deconstruct

Updating the README can happen in any branch to reflect changes, but just about everything else should have its own branch

- Adds a makefile & update REAMDE, 

- fix docker-compose, 
- Dependency changes,
- Add MySQL,

- add sequelize (to connect to mysql through NextJS) and required config, including initial models and migrations.

- Adds integration with MySQL database for creating paybuttons through the API Route /api/paybutton,
- social login changes,

2022-04-29 02:16 UTC, closed without merging