[Issue #493] feat: landing page
PayButton/paybutton-server pull request #590
Opened 2023-08-10 22:45 UTC by johnkuney

Related to #493 

Description
Adding a landing page to the app 

Test plan
Run the app and navigate to localhost:3000
Check out the page on different screens and browsers
Try dark mode toggle
Try logging in 
Rest of the app should function as normal 

Remarks
I know we want to ideally have separate pages for login vs sign up, but I am still looking into how to achieve this, so for now both buttons go to the same place

2023-08-10 23:11 UTC, Klakurka requested changes
- Obviously as you said, the Sign In & Sign Up buttons should point to the different dialogs if we can.
- Hide the Supporters section.

2023-08-11 02:31 UTC, johnkuney commented
Okay for sure, updated

2023-08-11 03:47 UTC, Klakurka requested changes
- Let's add a GitHub icon link in the header and footer. https://github.com/PayButton/ is a fine link I think since we have 2 main repos. Have this open in a new tab.
- Let's also add a link to the Telegram channel: https://t.me/paybutton. Have this open in a new tab.
- Just like I had mentioned before, the PayButton logo is for some reason a different colour as the rest of the text on the page (same off-dark-grey text colour as in the admin nav when logged in). Anything you think we should do about that?
![image](https://github.com/PayButton/paybutton-server/assets/4713204/fa29309c-8482-475a-9300-17e0455abe9c)

2023-08-11 03:47 UTC, Klakurka commented on components/LandingPage/GetStarted.tsx
> +          <span className={style.your_address}>YOUR_ADDRESS_HERE</span> with
There's a space missing to the left of the YOUR_ADDRESS_HERE text now.

2023-08-11 14:46 UTC, johnkuney commented
hmm thats still so weird on the logo being washed out. I cant recreate it. What about other images on the page? Like the background curves or dashboard image? 
![Uploading Screen Shot 2023-08-11 at 9.43.07 AM.png…]()

2023-08-11 20:39 UTC, Klakurka commented
- Landing page logos (in header and footer)
- Auth page logo (at top)
- Admin nav (all content)

2023-08-11 22:01 UTC, chedieck commented
> the Sign In & Sign Up buttons should point to the different dialogs if we can.

Do we have a task for this? Just created a PR #595

2023-08-11 22:15 UTC, Klakurka commented
> > the Sign In & Sign Up buttons should point to the different dialogs if we can.
> 
> Do we have a task for this? Just created a PR #595

No task open, just the one for visually differentiating the two pages.

2023-08-12 17:40 UTC, Klakurka commented
Note that the new signin/signup pages will have the following URLs `/signin` and `/signup` respectively so that will need to be changed too.

2023-08-14 22:27 UTC, Klakurka requested changes
The landing page redirects to /signin immediately which is an issue.

2023-08-14 22:29 UTC, johnkuney commented
ah for sure will take a look. Im actually still trying to get it to run with this new branch, so havent seen it yet

2023-08-14 22:49 UTC, johnkuney commented
okay should be good now

2023-08-14 23:03 UTC, Klakurka requested changes
- Can we add a copy button into the corner of the "Get Started" HTML section? I remember we had one w/ the button maker but I guess that was removed. It would be nice to have it if we could.
- Nit: Can we can a better blue 'pay' button where the corners are properly rounded? Could just take a screenshot from a zoomed in PayButton w/ that exact colours 
![image](https://github.com/PayButton/paybutton-server/assets/4713204/437002bf-5695-4bbf-a5e8-14a7aaa45274)
- Nit: How about getting a screenshot with slightly "better" data? It's weird/wrong to see "year total: 312" but then the chart only shows 0s and 1s for payment totals for each month. 
![image](https://github.com/PayButton/paybutton-server/assets/4713204/b2d5f324-6a5e-4374-a107-b443f6794d55)

2023-08-15 14:01 UTC, johnkuney commented
Yep for sure, do you have a good address that has some transaction data that would make for a good image? I didnt have a good one off hand

2023-08-15 17:10 UTC, Klakurka requested changes
- Github should be GitHub
- Signing into the admin panel has the landing page flash up for a second; probably out of scope for this specific branch but wanted to mention it.
- I can't seem to find a good mix of addresses for the chart screenshots so maybe you could just make them up if that's what you did for these? Just need to make sure that the math lines up otherwise somebody will think it's got a bug. The 'Revenue' side looks good but the 'Payments' side could use some variety.

2023-08-15 18:16 UTC, johnkuney commented
Okay for sure, any ideal values there for everything? Revenue amount is good? what about amount of buttons and payments?

2023-08-15 18:36 UTC, Klakurka commented
Maybe keep it under $30k for the year, something like that. Slow/gradual trend upwards over the year is also probably good.

2023-08-15 20:53 UTC, johnkuney commented
Okay added those and also went ahead and cleaned up the login pages here

2023-08-15 21:22 UTC, Klakurka requested changes
- /reset-password UI needs to be updated
- /verify UI needs to be updated (likely need to actually going through the sign up + verify process to actually see the page properly)
- If you're logged in, navigating to the landing page now redirects you back to the dashboard. We should allow people to visit the dashboard if they want to even if they're logged in. Bonus points would be to show 'Dashboard' and 'Sign Out' instead of 'Sign Up' and 'Sign In' in the nav but we can v2 this if it's too much trouble.

2023-08-16 13:43 UTC, johnkuney commented
hows that looking now? For the changing the nav if logged in I think will save for another PR

2023-08-16 16:18 UTC, Klakurka requested changes
- Let's stick with 'email' instead of 'e-mail' (/verify page). 
![image](https://github.com/PayButton/paybutton-server/assets/4713204/d131c5c6-7bb2-4bca-ae67-efe50f6a18ad)
- Let's change 'Forgot Password' to 'Reset Password' to match the /reset-password URL. 
![image](https://github.com/PayButton/paybutton-server/assets/4713204/c7a3961c-06db-4ddc-9ecd-b6d7b227ad0c)

2023-08-16 21:29 UTC, Klakurka approved these changes

2023-08-16 21:29 UTC, merged

2023-08-17 01:42 UTC, Klakurka commented
Still needs to get into `master`.