[#652]UI: Button generator advanced options
PayButton/paybutton-server pull request #691
Opened 2023-09-26 21:23 UTC by johnkuney

Related to #652

Description
---
Adding the advanced options to the button generator, as well as a toggle for the widget

Test plan
---
Go to the button generator and try the new options. Check the code output looks correct and the preview works

2023-09-27 22:51 UTC, Klakurka requested changes
Can't seem to build this branch.

![image](https://github.com/PayButton/paybutton-server/assets/4713204/78446041-6bcf-4f48-bfc0-0bc24eb7d56f)

2023-09-27 22:57 UTC, Klakurka commented
Same thing after a git prune.

2023-09-28 03:27 UTC, johnkuney commented
hmm maybe was behind some commits, just did a rebase

2023-09-28 06:53 UTC, Klakurka requested changes
Still getting the same error.

2023-10-03 00:50 UTC, Klakurka commented on components/ButtonGenerator/CodeBlock.tsx
> +        if (['USD', 'CAD', 'EUR', 'GBP', 'AUD'].includes(value)) {
I'd rather this come from a central list somewhere. Maybe from the DB. It'll be one of those things we miss when we add/remove currencies. In fact EUR, GPB, and AUD aren't even supported rn.

2023-10-03 19:19 UTC, johnkuney commented
Will revisit this with a more incremental approach since we are having issues with the branch

2023-10-03 19:19 UTC, closed without merging