[#732] fix: avoid tx holes
PayButton/paybutton-server pull request #754
Opened 2023-12-11 15:50 UTC by chedieck

Related to #732

Description
---
Make so we sync the missed transactions one address by one, and log the errors in case there are any.

Test plan
---
This can be tested in local dev by:
1. Have the containers running with `make dev` and some of your addresses in the database.
2. Stop all containers but the database one with `make stop-prod`
3. Make sure the database is up and running with `yarn docker db` and check how many txs you have on that address of yours with `SELECT count(*) FROM Address where address='ecash:youraddresshere';`
4. Transfer some XEC to that address
5. Build the project with `make prod` and make sure that after it is up the newly arrived tx is synced, that same counting query should return one more entry.

2023-12-12 06:50 UTC, Klakurka requested changes
The transactions appeared but one of them was not marked as confirmed:

<img width="466" alt="image" src="https://github.com/PayButton/paybutton-server/assets/4713204/744a5ffe-25aa-4db6-9eaa-b4c7efad8bc9">

How I did this was:

1. Start the server.
2. Make a payment to the address.
3. Shut down the non-db containers.
4. Make another payment to the address (I used the same amount for both to try to intentionally confuse it).
5. Wait for a block to come in.
6. Make another payment to the address.
7. Start the containers.
8. View the /button/ page.

2023-12-12 17:11 UTC, chedieck commented
> The transactions appeared but one of them was not marked as confirmed:

Nice catch, this should be fixed now.

2023-12-12 18:31 UTC, Klakurka requested changes
Works but checks are failing.

2023-12-12 18:43 UTC, chedieck commented
Fixed

2023-12-12 20:06 UTC, Klakurka requested changes
Unconfirmed txs don't show up as payments until confirmed if received while the server was down.

Also I have a missing payment.

<img width="513" alt="image" src="https://github.com/PayButton/paybutton-server/assets/4713204/9cd6cd25-cd81-4da3-bdac-72be4ea9116e">

<img width="431" alt="image" src="https://github.com/PayButton/paybutton-server/assets/4713204/eeaf3c14-f50c-43dd-8d23-38688a9c37d6">

2023-12-13 20:57 UTC, Klakurka approved these changes
Works for me now!

2023-12-13 20:57 UTC, Klakurka commented
If it does come up again, we can address it at that time.

2023-12-13 20:57 UTC, merged