[#798] feat: change hmac to signature
PayButton/paybutton-server pull request #820
Opened 2024-02-16 22:43 UTC by chedieck

Related to #798 

Description
---
Signs the POST request instead of using a hashmac.

The `<signature>` variable now is an object of the format:
```
{
  "payload": [variables present in the POST data concataned by + sign]
  "signature": [signature of the payload using the user's private key]
}
``` 
Therefore, users could form the payload themselves using their logic or just used the one we used out of the box.

Test plan
---
After receiving a POST request from a trigger, use the public key available in the **Account** view, the signature and the payload to verify integrity. An example I used on my running `staking` dev app:
```
import crypto from 'crypto'

interface Signature {
  payload: string
  signature: string
}

const verifySignature = (pubKey: string, signature: Signature) => {
  const pubKeyBuffer = Buffer.from(pubKey, 'hex')
  const publicKey = crypto.createPublicKey({ key: pubKeyBuffer, format: 'der', type: 'spki' });
  return crypto.verify(
    null,
    Buffer.from(signature.payload),
    publicKey,
    Buffer.from(signature.signature, 'hex')
  )
}

```  

 
Remarks
---

WIP:
- [ ] unittests to add
- [ ] better the **Account** view explanatory text

2024-02-17 22:06 UTC, Klakurka requested changes
I think I'd prefer to test this using the "simple nextjs server" when it's rdy.

Why not simplify it by exclusing the 'payload' and then just make it clear in the documentation how to do the concatenation?

2024-02-17 22:34 UTC, chedieck commented
> I think I'd prefer to test this using the "simple nextjs server" when it's rdy.

Ok

> Why not simplify it by exclusing the 'payload' and then just make it clear in the documentation how to do the concatenation?

Because however clear we make it, it still wouldn't be clear as seeing the thing itself. And since our rules of concatenation (variables present in the request, ordered alphabetically, + sign as separator, and the particularity of the OP_RETURN data) are not obvious, I think a lot of people would just prefer to use the already formed payload.

There is no insecurity in that as far as I can tell; we form the payload using the same variables we also send. Unless they go into the Blockchain themselves to see this variables, seeing the variables WE passed or seeing the concatenated string WE formed (from those same variables) is effectively the same.

2024-02-17 23:39 UTC, Klakurka requested changes
I'm also getting this error on the dashboard (it's blank but I found a link to it in dev tools):

<img width="801" alt="image" src="https://github.com/PayButton/paybutton-server/assets/4713204/e32f505b-cf9c-4480-bcd1-c55156c88ebe">

2024-02-22 22:43 UTC, Klakurka requested changes

2024-02-22 22:43 UTC, Klakurka commented on pages/account/index.tsx
> +              - payload: The transaction data variables present in the POST request concatenated using the plus (+) symbol as a separator
Add a period to the end of this.

2024-02-22 22:43 UTC, Klakurka commented on pages/account/index.tsx
> +              To verify, check variable &lt;signature&gt;, it should contain two keys:
To verify, check the &lt;signature&gt; variable. It should contain two keys:

2024-02-23 03:47 UTC, Klakurka submitted a review, later dismissed

2024-02-23 03:47 UTC, merged