[UI] Add Logged in User indicator
PayButton/paybutton-server pull request #877
Opened 2024-10-08 19:28 UTC by johnkuney

Related to #826

Description
---
Adding the user email to the top right of the screen across the pages to indicate who's logged in.
I also added a few minor UI tweaks and updated twitter to X 

As far as I can tell, there is not a way to get the email at the component level, so I had to add it to the getStaticProps for every page. But if there is a cleaner way to do this let me know @chedieck  

Test plan
---
Preview the site see the email appears on all the main pages. It should also link to /account

2024-10-08 19:39 UTC, Klakurka requested changes
- I think we can skip the account icon for now.
- Maybe we can make it styled more like the main nav buttons where hovering over it will change the bg of the button; on-hover underlining removed.
- I think it would look better if it was positioned at the top of the div like the page's <h2> is, rather then being postioned vertically centered.

2024-10-08 20:05 UTC, johnkuney commented
For sure, added

2024-10-08 20:53 UTC, Klakurka approved these changes

2024-10-09 03:01 UTC, chedieck requested changes
Left a suggestion and some code readability remarks

2024-10-09 17:45 UTC, johnkuney commented on pages/wallets/index.tsx
> +  user: UserWithSupertokens
'this.props.user.userProfile.id' right?

2024-10-09 17:45 UTC, johnkuney commented
Cool, added those changes

2024-10-10 01:38 UTC, chedieck commented on pages/wallets/index.tsx
> +  user: UserWithSupertokens
yep, indeed

2024-10-10 11:32 UTC, chedieck approved these changes
LGTM!

2024-10-10 14:05 UTC, Klakurka approved these changes

2024-10-10 14:06 UTC, merged