[#253] feat/send-email
PayButton/paybutton-server pull request #883
Opened 2024-10-26 01:50 UTC by chedieck

Related to #253

Description
---
1. Implements the email trigger.
2. Fixes bug where trigger couldn't be updated

Test plan
---
1. First put the new variables in `.env.local` and `paybutton-config.json`
2. Restart the containers
3. Set up a trigger to an email you own on a button with an address you own
4. Make a payment to that address
5. Ensure the email comes, the HTML formatted

Finally, check if the trigger email can be updated normally.

2024-10-26 03:05 UTC, Klakurka requested changes
Email didn't send - any logs?

2024-10-26 04:11 UTC, chedieck commented
> Email didn't send - any logs?

Yeah, success and errors are both logged into the TriggerLog table

2024-10-26 15:28 UTC, Klakurka requested changes
Ok looks good but let's fix up the actual email contents to be suitable for production.

At least:

 - Remove "WIP".
 - Remove "Testing variables and HTML".

2024-10-29 23:38 UTC, Klakurka approved these changes

2024-10-29 23:38 UTC, merged