Feat/user timezone
PayButton/paybutton-server pull request #908
Opened 2024-12-30 15:47 UTC by lissavxo

Related to #893 

Depends on
---
- [ #741]

Description
---
Implement timezone option in user Account settings. 
This PR will enable timezone option, the selector  is initialized with the timezone of the user by location, once user changes the selector value it will set the timezone and it will make the dashboard data, the txs listing of each button and payments listing to use the timezone selected. 

Test plan
---
Start the server with `docker compose up`
- Go to account page, check if selector is initialized with timezone of your location
- Change selector to another timezone
- Check payments list see if the date of each payment is in the preferred timezone  
- Check the transaction list in button page see if the date of each tx is in the preferred timezone 
- Check dashboard data, it should display the data according to the new timezone set

2025-01-01 00:25 UTC, Klakurka requested changes
If I change my account's time zone, the dashboard doesn't update to reflect the fact that txs made on a certain date in one time zone are actually a day ahead/behind in another.

2025-01-02 17:29 UTC, lissavxo commented
> If I change my account's time zone, the dashboard doesn't update to reflect the fact that txs made on a certain date in one time zone are actually a day ahead/behind in another.

I was not clearing cache after setting the timezone, now It should work

2025-01-03 19:10 UTC, Klakurka requested changes
I got this when trying to update my time zone:

![image](https://github.com/user-attachments/assets/d225d97c-5fb5-4aee-8a88-e03fb708e5c6)

2025-01-03 19:46 UTC, Klakurka requested changes
I changed the time zone a few times and eventually got this on `/payments`:

![image](https://github.com/user-attachments/assets/427e7899-d298-4d97-a766-7f0c728b149d)

2025-01-03 21:16 UTC, Klakurka approved these changes

2025-01-07 00:52 UTC, chedieck requested changes
Requested some changes in the code, also:

The other settings (Preferred currency & organization) give us feedback when they're updated. This could do the same as preferred currency, showing **"Updated timezone successfully"** after the update, or the error in case there is some.

2025-01-07 00:52 UTC, chedieck commented on pages/payments/index.tsx
> +      userProfile: user.userProfile
This seems really redundant. You're sending the samething twice, first `user` then `user.userProfile` as userProfile

2025-01-07 00:52 UTC, chedieck commented on redis/paymentCache.ts
> +  const dashboardData = await getUserDashboardData(userId, moment.tz.guess())
this doesn't seem right. It will be run in the server. I tested adding 
```
  console.log('WIP tz', moment.tz.guess(), typeof window, 'is window type')
```
right above this line and got
```
2|next  | 2025-01-07T00:45:35: WIP tz Africa/Abidjan undefined is window type
```

... as a result, which shows:
- guess is wrong
- is being run in the server, since this was in the **server** logs (not the browser console) and even shows that `typeof window === undefined`.

2025-01-07 19:03 UTC, chedieck commented on components/Timezone Selector/index.tsx
>        } catch (err: any) {
this should actually be at the else of the `if ` above. If the api runs into an error, it will return a status code 500 response message, not throw here.

2025-01-07 21:29 UTC, chedieck approved these changes

2025-01-07 22:24 UTC, merged